LOAD DATA LOCAL
  INFILE "/tmp/BILL_HISTORY_TBL.dat"
  REPLACE
  INTO TABLE capublic.bill_history_tbl
  FIELDS TERMINATED BY '\t'
  OPTIONALLY ENCLOSED BY '`'
  LINES TERMINATED BY '\n'
(
   BILL_ID
  ,BILL_HISTORY_ID
  ,ACTION_DATE
  ,ACTION
  ,TRANS_UID
  ,TRANS_UPDATE_DT
  ,ACTION_SEQUENCE
  ,ACTION_CODE
  ,ACTION_STATUS
  ,PRIMARY_LOCATION
  ,SECONDARY_LOCATION
  ,TERNARY_LOCATION
  ,END_STATUS
)


