LOAD DATA LOCAL
  INFILE "/tmp/BILL_MOTION_TBL.dat"
  REPLACE
  INTO TABLE capublic.bill_motion_tbl
  FIELDS TERMINATED BY '\t'
  OPTIONALLY ENCLOSED BY '`'
  LINES TERMINATED BY '\n'
(
   MOTION_ID
  ,MOTION_TEXT
  ,TRANS_UID
  ,TRANS_UPDATE
)
